name: beauty_products
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  connectivity_plus: ^6.1.5
  http: ^1.5.0

  dio: ^5.2.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  path_provider: 2.0.15
  image_picker: ^1.0.4
  crop_image: ^1.0.15
  permission_handler: ^12.0.1
  image_cropper: ^8.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  background_image: assets/images/aou_logo.png
  android: true
  ios: true
  android_12:
    image: assets/images/splash.png
    icon_background_color: "#ffffff"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aou_logo.png"
  min_sdk_android: 21
